[errorformat]
src.cmd = "gh api repos/reviewdog/errorformat/commits/master --jq .sha"
fetch.github = "reviewdog/errorformat"

[starlink-exporter]
src.github = "clarkzjw/starlink_exporter"
fetch.github = "clarkzjw/starlink_exporter"

[kubernetes-mcp-server]
src.github = "containers/kubernetes-mcp-server"
fetch.github = "containers/kubernetes-mcp-server"

[gitbucket]
src.github = "gitbucket/gitbucket"
fetch.url = "https://github.com/gitbucket/gitbucket/releases/download/$ver/gitbucket.war"

[prometheus-jmx-exporter]
src.github = "prometheus/jmx_exporter"
fetch.url = "https://github.com/prometheus/jmx_exporter/releases/download/$ver/jmx_prometheus_javaagent-$ver.jar"
