[errorformat]
src.cmd = "gh api repos/reviewdog/errorformat/commits/master --jq .sha"
fetch.github = "reviewdog/errorformat"

[starlink-exporter]
src.github = "clarkzjw/starlink_exporter"
fetch.github = "clarkzjw/starlink_exporter"

[kubernetes-mcp-server]
src.github = "containers/kubernetes-mcp-server"
fetch.github = "containers/kubernetes-mcp-server"
